name: "ci-master"

on: [push, pull_request]

jobs:
  run_tests:
    name: "Run all tests (CPU only)"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build test docker image and run all tests
        run: |
          chmod +x ./tests/run_tests.sh
          ./tests/run_tests.sh --build-docker --force-bootstrap --cpu-test
